// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// dmcCppR
List dmcCppR(List r_in);
RcppExport SEXP _DMCfun_dmcCppR(SEXP r_inSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type r_in(r_inSEXP);
    rcpp_result_gen = Rcpp::wrap(dmcCppR(r_in));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_DMCfun_dmcCppR", (DL_FUNC) &_DMCfun_dmcCppR, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_DMCfun(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
